name: CI - Registry

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      RELEASE_GO_VER: "1.22"

    steps:
    - name: Check out code
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

    - name: "Set up Go ${{ env.RELEASE_GO_VER }}"
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version: "${{ env.RELEASE_GO_VER }}"
        check-latest: true
      id: go

    - name: Build
      run: make binaries

    - name: Registry - Distribution
      run: make ci-distribution

    - name: Registry - Zot
      run: make ci-zot
